name: Parent Workflow

on: workflow_dispatch

jobs:
  init-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize Manual Actions
        run: |
          # Perform any initialization tasks here

      - name: Trigger Child Workflow
        uses: ./.github/workflows  # Path to the folder containing the child workflow
        with:
          workflow: install-tools.yml  # Name of the child workflow YAML file

  summarize:
    needs: init-actions
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get Child Workflow's Output
        id: child_output
        run: |
          echo "The child workflow output is: ${{ steps.install.outputs.workflow_run_output }}"
        
      - name: Print Summary Report
        run: |
          echo "Summary Report:"
          echo "Installed tools: Maven, Node.js, Java"
          echo "Child Workflow Output: ${{ steps.child_output.outputs.workflow_run_output }}"
